[package]
name = "onebot-connect-interface"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1" }
serde-value = {version = "0.7" }
onebot-types = { path = "../../onebot-types" }
thiserror = { version = "2" }
futures = { version = "0.3", optional = true, default-features = false}

[features]
default = ["client"]
server = []
client = []
client_recv = ["client", "futures"]
