[package]
name = "onebot-connect-interface"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "*" }
serde-value = {version = "*" }
onebot-types = { path = "../../onebot-types" }
thiserror = { version = "*" }
futures = { version = "*", optional = true }

[features]
default = ["client"]
server = []
client = []
client_recv = ["client", "futures"]
